[phases.setup]
nixPkgs = ["python39Full","gcc","python39Packages.pip","python39Packages.setuptools","python39Packages.wheel"]

[phases.install]
cmds = [
  "/opt/venv/bin/pip install --no-cache-dir numpy Cython",
  "/opt/venv/bin/pip install --no-cache-dir --no-build-isolation pkuseg",
  "/opt/venv/bin/pip install --no-cache-dir -r requirements.txt"
  
]

[start]
cmd = "uvicorn api:app --host 0.0.0.0 --port $PORT"